// A colour-space transform as Metal source, generated by OpenColorIO.
//
// The pipeline the compositor implements is the standard one: every layer is converted from its
// own space into a common linear working space, layers are blended *in that linear space* (adding
// light, which is what compositing physically is), and the result goes through one display
// transform at the end. Blending in display-encoded values — which is what a naive compositor
// does — darkens every cross-dissolve and edge.

import Foundation
import COCIO

public struct ColorLUT: Sendable {
    public let samplerName: String
    public let width: Int
    public let height: Int
    /// 0 for a 1D/2D LUT; N for an N³ 3D LUT.
    public let edgeLength: Int
    public let channels: Int
    public let nearest: Bool
    public let values: [Float]
}

public enum ColorTransformError: Error, CustomStringConvertible {
    case ocio(String)
    case needsLUTs(source: String, destination: String, count: Int)
    public var description: String {
        switch self {
        case .ocio(let m): return "OpenColorIO: \(m)"
        case .needsLUTs(let s, let d, let n):
            return "the transform \(s) → \(d) needs \(n) LUT texture(s), which the compositor does not yet upload. "
                 + "Refusing rather than rendering wrong colour. (Every ACES path in the built-in config is analytic and works.)"
        }
    }
}

/// One OCIO transform, compiled to Metal Shading Language.
public struct ColorTransform: Sendable {
    public let config: String
    public let source: String
    public let destination: String
    /// The MSL function name to call: `float4 name(float4)`.
    public let functionName: String
    /// Complete MSL — a struct wrapper plus the free function. Prepended to the compositor source.
    public let msl: String
    public let luts: [ColorLUT]

    public static let defaultConfig = "ocio://default"   // OCIO 2.5 ships the ACES cg-config

    public init(config: String = ColorTransform.defaultConfig,
                from source: String, to destination: String, functionName: String) throws {
        var err: UnsafeMutablePointer<CChar>?
        guard let handle = sharpy_ocio_create(config, source, destination, functionName, &err) else {
            let message = err.map { String(cString: $0) } ?? "unknown error"
            if let err { sharpy_ocio_string_free(err) }
            throw ColorTransformError.ocio(message)
        }
        defer { sharpy_ocio_destroy(handle) }

        self.config = config
        self.source = source
        self.destination = destination
        self.functionName = functionName
        self.msl = sharpy_ocio_shader_text(handle).map { String(cString: $0) } ?? ""

        var luts: [ColorLUT] = []
        for i in 0..<sharpy_ocio_texture_count(handle) {
            var t = SharpyOCIOTexture()
            guard sharpy_ocio_texture(handle, i, &t) == 1 else { continue }
            let count = Int(t.valueCount)
            var values = [Float](repeating: 0, count: count)
            if let p = t.values, count > 0 { values.withUnsafeMutableBufferPointer { $0.baseAddress!.update(from: p, count: count) } }
            luts.append(ColorLUT(samplerName: t.samplerName.map { String(cString: $0) } ?? "",
                                 width: Int(t.width), height: Int(t.height), edgeLength: Int(t.edgelen),
                                 channels: Int(t.channels), nearest: t.nearest == 1, values: values))
        }
        self.luts = luts
        // A transform whose LUTs we cannot bind would silently render wrong colour. Refuse instead.
        if !luts.isEmpty { throw ColorTransformError.needsLUTs(source: source, destination: destination, count: luts.count) }
    }

    /// Colour spaces available in a config.
    public static func colorSpaces(config: String = ColorTransform.defaultConfig) throws -> [String] {
        var err: UnsafeMutablePointer<CChar>?
        guard let list = sharpy_ocio_list_colorspaces(config, &err) else {
            let message = err.map { String(cString: $0) } ?? "unknown error"
            if let err { sharpy_ocio_string_free(err) }
            throw ColorTransformError.ocio(message)
        }
        defer { sharpy_ocio_string_free(list) }
        return String(cString: list).split(separator: "\n").map(String.init)
    }

    public static var ocioVersion: String { sharpy_ocio_version().map { String(cString: $0) } ?? "unknown" }
}

/// What the compositor applies: each layer in, the blend result out.
public struct ColorPipeline: Sendable {
    /// Source space → linear working space, applied per layer before blending.
    public let input: ColorTransform?
    /// Working space → display, applied once after blending.
    public let output: ColorTransform?

    public init(input: ColorTransform?, output: ColorTransform?) { self.input = input; self.output = output }

    /// The common case: footage in `sourceSpace`, blended linearly, shown on `displaySpace`.
    public init(from sourceSpace: String, working: String = "Linear Rec.709 (sRGB)",
                to displaySpace: String = "sRGB - Display",
                config: String = ColorTransform.defaultConfig) throws {
        self.input = sourceSpace == working ? nil : try ColorTransform(config: config, from: sourceSpace, to: working, functionName: "SharpyInputTransform")
        self.output = working == displaySpace ? nil : try ColorTransform(config: config, from: working, to: displaySpace, functionName: "SharpyOutputTransform")
    }

    /// Identity — used when footage is already display-referred and no grade is wanted.
    public static let passthrough = ColorPipeline(input: nil, output: nil)

    public var isIdentity: Bool { input == nil && output == nil }

    /// MSL prelude: both generated transforms, plus identity stubs for whichever is absent so the
    /// kernel body can call them unconditionally.
    var mslPrelude: String {
        var out = ""
        if let input { out += input.msl + "\n" } else { out += "static inline float4 SharpyInputTransform(float4 c) { return c; }\n" }
        if let output { out += output.msl + "\n" } else { out += "static inline float4 SharpyOutputTransform(float4 c) { return c; }\n" }
        return out
    }
}
